name: SneakyMisc
version: "1.0"
main: com.danidipp.sneakymisc.SneakyMisc
api-version: "1.20"
authors:
  - DaniDipp
description: "Paper plugin for Lords of Minecraft mechanics that don't justify having a plugin of their own"
dependencies:
  server:
    SneakyCharacterManager:
      load: BEFORE
      required: false
    SneakyPocketbase:
      load: BEFORE
      required: true